In [ ]:
from datasets import load_dataset

In [ ]:
dataset = load_dataset("abdullah693/adaption-urdu-edu-cultural-reasoning")
print(dataset['train'][0])

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:124: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

{'prompt': 'ایک چیز کا وزن زمین کی سطح پر 10 کلوگرام ہے۔ اگر اسی چیز کو مریخ کی سطح پر لے جایا جائے، تو اس کا وزن 3.8 کلوگرام ہو جائے گا۔ زمین سے مریخ لے جانے پر چیز کے وزن میں تبدیلی کی بہترین وضاحت کون سی ہے؟\n\nآپشنز:\nA) چیز کی کثافت زمین پر مریخ کے مقابلے میں زیادہ ہے۔\nB) چیز کا حجم زمین پر مریخ کے مقابلے میں زیادہ ہے۔\nC) کشش ثقل کی قوت زمین پر مریخ کے مقابلے میں زیادہ ہے۔\nD) فضائی دباؤ زمین پر مریخ کے مقابلے میں کم ہے۔', 'completion': 'درست جواب (C) ہے: کشش ثقل کی قوت زمین پر مریخ کے مقابلے میں زیادہ ہے۔', 'enhanced_prompt': 'درج ذیل سائنسی سوال کا تجزیہ کریں اور دیے گئے آپشنز میں سے بہترین وضاحت کا انتخاب کریں:\n\nسوال:\nایک چیز کا وزن زمین کی سطح پر 10 کلوگرام ہے۔ اگر اسی چیز کو مریخ کی سطح پر لے جایا جائے، تو اس کا وزن 3.8 کلوگرام ہو جائے گا۔ زمین سے مریخ لے جانے پر چیز کے وزن میں تبدیلی کی بہترین وضاحت کون سی ہے؟\n\nآپشنز:\nA) چیز کی کثافت زمین پر مریخ کے مقابلے میں زیادہ ہے۔\nB) چیز کا حجم زمین پر مریخ کے مقابلے میں زیادہ ہے۔\nC) کشش ثقل کی قوت زمین پر مریخ کے مقابلے میں زیادہ ہے۔\nD) فضائی دباؤ زمین پر مریخ کے مقابلے میں کم ہے۔\n\nہدایات:\n1. وزن اور کمیت (mass) کے فرق کو مدنظر رکھتے ہوئے کشش ثقل (gravity) کے اثرات کا جائزہ لیں۔\n2. تعین کریں کہ کون سا آپشن وزن میں تبدیلی کی درست سائنسی وجہ بیان کرتا ہے۔\n3. صرف درست آپشن کا حرف (A, B, C, یا D) اور اس کی مختصر وجہ فراہم کریں۔', 'enhanced_completion': 'درست آپشن: C\n\nوجہ: وزن دراصل وہ قوت ہے جس سے کوئی سیارہ کسی چیز کو اپنی طرف کھینچتا ہے، جبکہ کمیت (mass) مستقل رہتی ہے۔ چونکہ زمین کی کشش ثقل مریخ کے مقابلے میں زیادہ ہے، اس لیے اسی چیز کا وزن زمین پر زیادہ اور مریخ پر کم ہوگا، جبکہ اس کی کمیت دونوں جگہوں پر یکساں رہے گی۔', 'reasoning_trace': "Let me break down this science question. The problem states that an object weighs 10 kg on Earth and 3.8 kg on Mars. I need to identify the best explanation for this change in weight from the given options.\n\nFirst, I need to carefully consider the difference between mass and weight, as the prompt's instructions explicitly tell me to do. Mass is an intrinsic property of an object—it doesn't change regardless of location. Weight, on the other hand, is the force of gravity acting on that mass (W = m * g). Since the mass remains constant, the change in weight must be due to a change in the gravitational acceleration (g).\n\nNow let's evaluate the options:\nOption A mentions density. The density of the object doesn't change just by moving it to a different planet, and density doesn't determine weight in this context.\nOption B mentions volume. Like density, the volume of a solid object remains the same, and it doesn't explain the change in weight.\nOption C states that the force of gravity is greater on Earth compared to Mars. This aligns perfectly with the physics principle I just considered. Earth is larger and more massive than Mars, so its gravitational acceleration is greater (roughly 9.8 m/s² vs 3.7 m/s²). Because g is smaller on Mars, the weight of the exact same mass is reduced. This is the correct scientific reason.\nOption D mentions atmospheric pressure. While atmospheric pressure differs greatly between Earth and Mars, it doesn't determine an object's weight in this manner; gravity does.\n\nTherefore, Option C is the correct choice. The instructions ask for just the letter and a brief reason. I'll formulate the final response stating C, and briefly explain that weight is the force of gravity acting on a constant mass, and since Earth's gravity is stronger than Mars's, the weight is greater on Earth.", 'domain': 'stem', 'id': 'arc_easy-1374', 'lang': 'en', 'needs_adaptation': True, 'source': 'arc_easy'}

In [ ]:
urdu_data = dataset['train'].filter(lambda x: x['lang'] == 'ur')
print(f"Urdu rows: {len(urdu_data)}")
print(urdu_data[0])

Filter:   0%|          | 0/39913 [00:00<?, ? examples/s]

Urdu rows: 18307
{'prompt': 'درج ذیل شعر کس شاعر کا ہے؟\n\nپھول بن کے سیروں میں اور کون شامل تھا\nشوخی صبا سے تو بالیاں نہیں کھلتیں', 'completion': 'یہ شعر پروین شاکر کا ہے۔', 'enhanced_prompt': 'درج ذیل شعر کا شاعر کون ہے؟\n\n"پھول بن کے سیروں میں اور کون شامل تھا\nشوخی صبا سے تو بالیاں نہیں کھلتیں"', 'enhanced_completion': 'یہ خوبصورت شعر اردو کے نامور شاعر **احمد فراز** کا ہے۔ فراز صاحب کے کلام میں روایت اور جدیدیت کا جو لطیف امتزاج ملتا ہے، یہ مصرعے اس کی بہترین مثال ہیں۔ انہوں نے فطرت کے استعاروں، جیسے صبا اور پھول، کے ذریعے انسانی احساسات کی عکاسی بڑی خوبصورتی سے کی ہے۔ "شوخیِ صبا" سے "بالیاں کھلنا" ایسی تخلیقی تصویر کشی ہے جو ان کی رومانوی شاعری کی خاص پہچان رہی ہے۔ اس شعر میں بتایا گیا ہے کہ باغ میں پھولوں کا کھلنا محض صبح کی ہوا کا نتیجہ نہیں تھا، بلکہ اس میں محبوب کی موجودگی اور رفاقت بھی شامل تھی، جس نے پھولوں کو کھلنے پر مجبور کیا۔ یہ غزل ان کے کلام کا ایک یادگار اور مقبول حصہ ہے۔', 'reasoning_trace': 'یہ شعر تو فوراً ذہن میں آ گیا ہے۔ "پھول بن کے سیروں میں اور کون شامل تھا / شوخی صبا سے تو بالیاں نہیں کھلتیں" — یہ احمد فراز کا شعر ہے۔ ان کی رومانوی شاعری کی یہ پہچان ہے کہ وہ فطرت کے معمولی مناظر میں بھی محبوب کی جلوہ گری کو تلاش کر لیتے ہیں۔ \n\nاب ذرا اس کے تخیلاتی پہلو پر غور کیا جائے۔ فراز صاحب نے \'صبا\' یعنی صبح کی ہوا اور \'پھولوں کا کھلنا\' جیسے روایتی استعاروں کو تو لیا ہے، لیکن انہیں اپنے مخصوص انداز میں گھما کر پیش کیا ہے۔ عام طور پر شعراء کہتے آئے ہیں کہ صبا کی شوخی سے پھول کھلتے ہیں، لیکن فراز یہاں اس روایت کو چیلنج کر رہے ہیں۔ وہ کہتے ہیں کہ صبا کی شوخی سے تو بالیاں نہیں کھلتیں، یعنی محض موسم کی تبدیلی یا ہوا کے جھونکوں سے پھولوں کے غنچے نہیں کھلتے۔ اگر ایسا ہوتا تو پھول کھل جاتے، لیکن ان کا کھلنا اس بات کی دلیل ہے کہ اس میں کوئی اور ہی وجہ شامل تھی۔ \n\nپھر پہلے مصرعے کا ربط بنتا ہے — "پھول بن کے سیروں میں اور کون شامل تھا"۔ یہاں وہ اشارہ کر رہے ہیں کہ پھولوں کے کھلنے میں محبوب کی رفاقت اور موجودگی شامل تھی۔ یہ محبت کی وہ تاثیر ہے جو فطرت کو بھی متاثر کرتی ہے۔ غنچوں کا کھلنا محض ایک قدرتی عمل نہیں رہا، بلکہ یہ محبوب کی آمد اور اس کی محبت کا اثر ہے۔ \n\nیہ احمد فراز کی شاعری کا وہ مخصوص اسلوب ہے جہاں وہ بیرونی مناظر کو دلی احساسات کے تابع کر دیتے ہیں۔ ان کی رومانوی شاعری میں روایت اور جدیدیت کا یہ لطیف امتزاج کہیں نہیں کہیں نظر آتا ہے۔ یہ غزل ان کے کلام کا ایک مقبول اور یادگار حصہ ہے، اور اس شعر میں ان کی تخلیقی تصویر کشی کا جو مظاہرہ ہے، وہ ان کی پہچان بن چکا ہے۔ ٹھیک اسی طرح سے میں اس کا جواب مرتب کروں گا۔', 'domain': 'urdu_literature', 'id': 'urdu_poetry-1671', 'lang': 'ur', 'needs_adaptation': False, 'source': 'urdu_poetry'}

In [ ]:
def format_data(row):
  return {
      "text": f"### Instruction:\n{row['prompt']}\n\n### Response:\n{row['enhanced_completion']}"
  }

formatted_data = urdu_data.map(format_data)
print(formatted_data[0]['text'])

### Instruction:
درج ذیل شعر کس شاعر کا ہے؟

پھول بن کے سیروں میں اور کون شامل تھا
شوخی صبا سے تو بالیاں نہیں کھلتیں

### Response:
یہ خوبصورت شعر اردو کے نامور شاعر **احمد فراز** کا ہے۔ فراز صاحب کے کلام میں روایت اور جدیدیت کا جو لطیف امتزاج ملتا ہے، یہ مصرعے اس کی بہترین مثال ہیں۔ انہوں نے فطرت کے استعاروں، جیسے صبا اور پھول، کے ذریعے انسانی احساسات کی عکاسی بڑی خوبصورتی سے کی ہے۔ "شوخیِ صبا" سے "بالیاں کھلنا" ایسی تخلیقی تصویر کشی ہے جو ان کی رومانوی شاعری کی خاص پہچان رہی ہے۔ اس شعر میں بتایا گیا ہے کہ باغ میں پھولوں کا کھلنا محض صبح کی ہوا کا نتیجہ نہیں تھا، بلکہ اس میں محبوب کی موجودگی اور رفاقت بھی شامل تھی، جس نے پھولوں کو کھلنے پر مجبور کیا۔ یہ غزل ان کے کلام کا ایک یادگار اور مقبول حصہ ہے۔

In [ ]:
import torch
print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0))

True
Tesla T4

In [ ]:
from unsloth import FastLanguageModel

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = 'unsloth/llama-3.2-3b-instruct',
    max_seq_length = 2040,
    load_in_4bit = True
)

==((====))==  Unsloth 2026.6.9: Fast Llama patching. Transformers: 5.5.0.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.10.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Loading weights:   0%|          | 0/254 [00:00<?, ?it/s]

Unsloth: Will load unsloth/llama-3.2-3b-instruct-unsloth-bnb-4bit as a legacy tokenizer.

In [ ]:
model = FastLanguageModel.get_peft_model(
    model,
    r=16,
    target_modules=[
        'q_proj', 'k_proj', 'v_proj', 'o_proj'
    ],
    lora_alpha = 16,
    lora_dropout = 0,
    bias = 'none'
)

Not an error, but Unsloth cannot patch MLP layers with our manual autograd engine since either LoRA adapters
are not enabled or a bias term (like in Qwen) is used.
Unsloth 2026.6.9 patched 28 layers with 28 QKV layers, 28 O layers and 0 MLP layers.

In [ ]:
from trl import SFTTrainer
from transformers import TrainingArguments

In [ ]:
trainer = SFTTrainer(
    model=model,
    tokenizer=tokenizer,
    train_dataset=formatted_data,
    dataset_text_field="text",
    max_seq_length = 2024,
    args=TrainingArguments(
        per_device_train_batch_size=2,
        gradient_accumulation_steps=4,
        warmup_steps=10,
        max_steps=100,
        learning_rate=2e-4,
        fp16=True,
        logging_steps=10,
        output_dir='outputs',
        save_strategy='no'
    ),

)

Unsloth: Tokenizing ["prompt"+"completion"] (num_proc=6):   0%|          | 0/18307 [00:00<?, ? examples/s]

In [ ]:
trainer.train()

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 18,307 | Num Epochs = 1 | Total steps = 100
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"     Trainable parameters = 9,175,040 of 3,221,924,864 (0.28% trained)

TrainOutput(global_step=100, training_loss=1.212535057067871, metrics={'train_runtime': 207.6235, 'train_samples_per_second': 3.853, 'train_steps_per_second': 0.482, 'total_flos': 3871787783479296.0, 'train_loss': 1.212535057067871, 'epoch': 0.043696744592527856})

In [ ]:
model.save_pretrained('urdu_model')
tokenizer.save_pretrained('urdu_model')
print("Model Saved")

Unsloth: Restored added_tokens_decoder metadata in urdu_model/tokenizer_config.json.

Model Saved

In [ ]:
from google.colab import userdata
from huggingface_hub import login

login(token=userdata.get('HF_TOKEN_WRITE'))

In [ ]:
from huggingface_hub import whoami
print(whoami()['name'])

mfayazkhan

In [ ]:
model.push_to_hub('mfayazkhan/UrduGPT')
tokenizer.push_to_hub('mfayazkhan/UrduGPT')

README.md:   0%|          | 0.00/584 [00:00<?, ?B/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...adapter_model.safetensors:   0%|          | 26.1kB / 36.7MB

Saved model to https://huggingface.co/mfayazkhan/UrduGPT

Unsloth: Restored added_tokens_decoder metadata in /tmp/tmp60nox1l2/tokenizer_config.json.

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...mp60nox1l2/tokenizer.json: 100%|##########| 17.2MB / 17.2MB

In [ ]:
FastLanguageModel.for_inference(model)

input = tokenizer(
    "### Instruction:\nاحمد فراز کون ہیں؟\n\n### Response:\n",
    return_tensors='pt'
).to('cuda')

outputs = model.generate(**input, max_new_tokens=200)
print(tokenizer.decode(outputs[0], skip_special_tokens=True))

Both `max_new_tokens` (=200) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:71: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:281: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:71: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:281: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)

### Instruction:
احمد فراز کون ہیں؟

### Response:
احمد فراز ایک پاکستانی سیاست دان ہیں جو 2023 کے پاکستانی عام انتخابات میں پاکستان مسلم لیگ (ن) کی امیدوار کے طور پر کراچی-5 حلقہ سے صوبائی اسمبلی کے لیے منتخب ہوئے۔

In [ ]:
from unsloth import FastLanguageModel

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name='mfayazkhan/UrduGPT',
    max_seq_length=2040,
    load_in_4bit=True
)

==((====))==  Unsloth 2026.6.9: Fast Llama patching. Transformers: 5.5.0.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.10.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

<string>:42: UserWarning: You passed `quantization_config` or equivalent parameters to `from_pretrained` but the model you're loading already has a `quantization_config` attribute. The `quantization_config` from the model will be used.

Loading weights:   0%|          | 0/254 [00:00<?, ?it/s]

Unsloth: Will load unsloth/llama-3.2-3b-instruct-unsloth-bnb-4bit as a legacy tokenizer.

adapter_model.safetensors:   0%|          | 0.00/36.7M [00:00<?, ?B/s]

In [ ]:
model = FastLanguageModel.get_peft_model(
    model,
    r=16,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj"],
    lora_alpha=16,
    lora_dropout=0,
    bias="none",
)

Unsloth: Already have LoRA adapters! We shall skip this step.

In [ ]:
trainer = SFTTrainer(
    model=model,
    tokenizer=tokenizer,
    train_dataset=formatted_data,
    dataset_text_field="text",
    max_seq_length = 2024,
    args=TrainingArguments(
        per_device_train_batch_size=2,
        gradient_accumulation_steps=4,
        warmup_steps=10,
        max_steps=600,
        learning_rate=2e-4,
        fp16=True,
        logging_steps=10,
        output_dir='outputs',
        save_strategy='no'
    ),

)

In [ ]:
trainer.train()

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 18,307 | Num Epochs = 1 | Total steps = 600
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"     Trainable parameters = 9,175,040 of 3,221,924,864 (0.28% trained)

TrainOutput(global_step=600, training_loss=1.1507470719019572, metrics={'train_runtime': 1344.1365, 'train_samples_per_second': 3.571, 'train_steps_per_second': 0.446, 'total_flos': 2.3577780653420544e+16, 'train_loss': 1.1507470719019572, 'epoch': 0.26218046755516716})

In [ ]:
model.save_pretrained('urdu_model-v2')
tokenizer.save_pretrained('urdu_model-v2')
print("Model Saved")

Unsloth: Restored added_tokens_decoder metadata in urdu_model-v2/tokenizer_config.json.

Model Saved

In [ ]:
# 2. Pack it into a zip file
import shutil
shutil.make_archive("urdu_model-v2", 'zip', "urdu_model-v2")

'/content/urdu_model-v2.zip'

In [ ]:
model.push_to_hub('mfayazkhan/UrduGPT-v2')
tokenizer.push_to_hub('mfayazkhan/UrduGPT-v2')

README.md:   0%|          | 0.00/584 [00:00<?, ?B/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...adapter_model.safetensors:   0%|          | 26.1kB / 36.7MB

Saved model to https://huggingface.co/mfayazkhan/UrduGPT-v2

Unsloth: Restored added_tokens_decoder metadata in /tmp/tmpp4b6qg1n/tokenizer_config.json.

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...mpp4b6qg1n/tokenizer.json: 100%|##########| 17.2MB / 17.2MB

In [ ]:
FastLanguageModel.for_inference(model)

input = tokenizer(
    "### Instruction:\nمرزا غالب کون ہیں؟\n\n### Response:\n",
    return_tensors='pt'
).to('cuda')

outputs = model.generate(**input, max_new_tokens=200)
print(tokenizer.decode(outputs[0], skip_special_tokens=True))

NameError: name 'FastLanguageModel' is not defined